name: delete-old-runs
on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  workflow_dispatch: null

jobs:
  delete-old-runs:
    name: delete-old-runs
    runs-on: "ubuntu-latest"
    steps:
      - name: generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CF_CURATOR_APP_ID }}
          private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

      - name: get env file
        shell: bash -l {0}
        run: |
          wget https://raw.githubusercontent.com/conda-forge/repodata-tools/main/environment.yml

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: delete runs
        shell: bash -l {0}
        run: |
          echo "\
          import github
          import os
          import sys
          import requests
          
          gh = github.Github(os.environ['GITHUB_TOKEN'])
          r = gh.get_repo('conda-forge/repodata-shards')
          done = 0
          for w in r.get_workflows():
              for _ in range(10):
                  skip_one = True
                  for rn in w.get_runs():
                      if rn.status == 'completed' and rn.conclusion in ['success', 'cancelled']:
                          if skip_one:
                              skip_one = False
                              continue
                          requests.delete(
                              rn.url, 
                              headers={'Authorization': 'Bearer ' + os.environ['GITHUB_TOKEN']},
                          )
                          done += 1
                      if done == 2000:
                          sys.exit(0)
          " > del_old_runs.py
          
          python del_old_runs.py
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
