on:
#   schedule:
#     - cron:  '15 * * * *'
  push:
    branches: 
      - master

jobs:
  update_shards:
    name: update repodata shards
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 0
          fetch-depth: 0
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.7
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
      - name: get repodata shards
        shell: bash -l {0}
        run: |
          conda install -y -q git

          git config --global user.email 'becker.mr@gmail.com'
          git config --global user.name 'beckermr'
          git config --global pull.rebase false

          pushd ..
          git clone --depth=1 https://github.com/regro/repodata-tools.git
          rt_pth=`pwd`/repodata-tools
          popd

          conda install -y -q --file ${rt_pth}/requirements.txt

          pushd ${GITHUB_WORKSPACE}

          repo_url=https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git remote set-url --push origin ${repo_url}

          python ${rt_pth}/scripts/make_anaconda_shards.py

          popd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
