name: update-shards-1

on:
  schedule:
    - cron:  '15 */2 * * *'
  workflow_dispatch: null

jobs:
  update_shards:
    name: update repodata shards
    runs-on: "ubuntu-latest"
    steps:
      - name: turnstyle
        uses: beckermr/turnstyle-python@v1
        with:
          poll-interval-seconds: 5
          abort-after-seconds: 10
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get env file
        shell: bash -l {0}
        run: |
          wget https://raw.githubusercontent.com/conda-forge/repodata-tools/main/environment.yml

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: install code
        shell: bash -l {0}
        run: |
          git config --global user.email "79913779+conda-forge-curator[bot]@users.noreply.github.com"
          git config --global user.name "conda-forge-curator[bot]"
          git config --global pull.rebase false

          pushd ..
          git clone --depth=1 https://github.com/conda-forge/repodata-tools.git
          pushd repodata-tools
          pip install -e .
          popd
          popd

      - name: generate token shards
        id: generate_token_shards
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CF_CURATOR_APP_ID }}
          private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

      - name: get repodata shards
        shell: bash -l {0}
        run: |
          export RANK=1
          export SYNC_STEP=shards
          source index_shards.sh
        env:
          GITHUB_TOKEN: ${{ steps.generate_token_shards.outputs.token }}
          BINSTAR_TOKEN: ${{ secrets.PROD_BINSTAR_TOKEN }}

      - name: generate token releases
        id: generate_token_releases
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CF_CURATOR_APP_ID }}
          private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

      - name: sync releases
        shell: bash -l {0}
        run: |
          export RANK=1
          export SYNC_STEP=releases
          source index_shards.sh
        env:
          GITHUB_TOKEN: ${{ steps.generate_token_releases.outputs.token }}
          BINSTAR_TOKEN: ${{ secrets.PROD_BINSTAR_TOKEN }}
