name: update-shards-1

on:
  schedule:
    - cron:  '15 * * * *'
  workflow_dispatch: null

jobs:
  update_shards:
    name: update repodata shards
    runs-on: "ubuntu-latest"
    steps:
      - name: turnstyle
        uses: beckermr/turnstyle-python@v1
        with:
          poll-interval-seconds: 5
          abort-after-seconds: 10
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CF_CURATOR_APP_ID }}
          private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get env file
        shell: bash -l {0}
        run: |
          wget https://raw.githubusercontent.com/conda-forge/repodata-tools/master/environment.yml

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: get repodata shards
        shell: bash -l {0}
        run: |
          export RANK=1
          source index_shards.sh
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          BINSTAR_TOKEN: ${{ secrets.PROD_BINSTAR_TOKEN }}
